// This file is @generated by prost-build.
/// ProcessContext represents the payload for the process context sharing mechanism.
///
/// This message is designed to be published by OpenTelemetry SDKs via a memory-mapped
/// region, allowing external readers (such as the OpenTelemetry eBPF Profiler) to
/// discover and read resource attributes from instrumented processes without requiring
/// direct integration or process activity.
#[cfg_attr(feature = "with-schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[cfg_attr(feature = "with-serde", serde(default))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessContext {
    /// The resource attributes describing this process.
    #[prost(message, optional, tag = "1")]
    pub resource: ::core::option::Option<super::super::resource::v1::Resource>,
    /// Additional attributes to share with external readers that are not part of
    /// the standard Resource. \[Optional\]
    #[prost(message, repeated, tag = "2")]
    pub extra_attributes: ::prost::alloc::vec::Vec<super::super::common::v1::KeyValue>,
}
